import json
import re

from services.llm_service import ask_llm

from models.conversation import (
    Conversation,
    ConversationMessage
)


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are an Enterprise AI Compliance Assistant.

You answer workplace compliance questions naturally and accurately.

The supplied compliance information is the source of truth for
specific Acts, particulars, and descriptions.

Use the conversation history and current context to understand
references such as:

- "this Act"
- "this particular"
- "why is this required?"
- "what about another country?"
- "what about another industry?"

Rules:

1. Never invent compliance facts.

2. If the supplied compliance information does not contain enough
   information, clearly say that more information is required.

3. Explain compliance concepts naturally rather than responding
   with menus unless the user is explicitly selecting an option.

4. Maintain the current conversation context.

5. If the user changes country or industry, acknowledge the change.

6. Keep answers concise but useful.

7. You are a compliance information assistant and not a substitute
   for professional legal advice.
"""


# ============================================================
# CONVERSATION
# ============================================================

def get_or_create_conversation(
    session_id,
    db
):

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == session_id
        )
        .first()
    )

    if conversation:
        return conversation


    conversation = Conversation(
        id=session_id,
        title="New Conversation"
    )

    db.add(conversation)
    db.commit()
    db.refresh(conversation)

    return conversation


# ============================================================
# GET CONVERSATION HISTORY
# ============================================================

def get_conversation_history(
    session_id,
    db,
    limit=20
):

    messages = (
        db.query(ConversationMessage)
        .filter(
            ConversationMessage.conversation_id == session_id
        )
        .order_by(
            ConversationMessage.created_at.asc()
        )
        .limit(limit)
        .all()
    )


    return [
        {
            "role": message.sender,
            "content": message.message
        }
        for message in messages
    ]


# ============================================================
# SAVE MESSAGE
# ============================================================

def save_message(
    session_id,
    sender,
    message,
    db,
    message_data=None
):

    conversation = get_or_create_conversation(
        session_id,
        db
    )


    conversation_message = ConversationMessage(
        conversation_id=session_id,
        sender=sender,
        message=message,
        message_data=message_data
    )


    db.add(conversation_message)

    db.commit()
    db.refresh(conversation_message)


    return conversation_message


# ============================================================
# CLEAN BAD LLM FORMATTING
# ============================================================

def clean_llm_formatting(text: str) -> str:

    if not text:
        return ""


    # --------------------------------------------------------
    # NORMALIZE LINE BREAKS
    # --------------------------------------------------------

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")


    # --------------------------------------------------------
    # REMOVE CODE BLOCK MARKERS
    # --------------------------------------------------------

    text = re.sub(
        r"```markdown",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = text.replace(
        "```",
        ""
    )


    # --------------------------------------------------------
    # REMOVE TABLE SEPARATOR LINES
    #
    # Examples:
    #
    # | ----- | ----- |
    # |:----- | -----:|
    # --------------------------------------------------------

    text = re.sub(
        r"\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)+\|?",
        "",
        text
    )


    # --------------------------------------------------------
    # SPLIT PIPE-BASED CONTENT
    #
    # This handles malformed Markdown tables generated by the LLM.
    # --------------------------------------------------------

    lines = text.split("\n")

    cleaned_lines = []


    for line in lines:

        stripped = line.strip()


        # Skip completely empty lines temporarily
        if not stripped:

            cleaned_lines.append("")
            continue


        # ----------------------------------------------------
        # HANDLE PIPE CONTENT
        # ----------------------------------------------------

        if "|" in stripped:

            cells = [
                cell.strip()
                for cell in stripped.split("|")
                if cell.strip()
            ]


            # If multiple cells exist, convert them into
            # readable bullet points.
            if len(cells) >= 2:

                # Handle pairs nicely
                if len(cells) == 2:

                    cleaned_lines.append(
                        f"- **{cells[0]}:** {cells[1]}"
                    )

                else:

                    # Convert each cell into separate readable line
                    for cell in cells:

                        cleaned_lines.append(
                            f"- {cell}"
                        )

                continue


            # If only one useful cell remains
            elif len(cells) == 1:

                cleaned_lines.append(
                    cells[0]
                )

                continue


        # ----------------------------------------------------
        # NORMAL CONTENT
        # ----------------------------------------------------

        cleaned_lines.append(
            stripped
        )


    text = "\n".join(cleaned_lines)


    # --------------------------------------------------------
    # REMOVE EMPTY BULLETS
    # --------------------------------------------------------

    text = re.sub(
        r"(?m)^-\s*$",
        "",
        text
    )


    # --------------------------------------------------------
    # REMOVE EXCESSIVE BLANK LINES
    # --------------------------------------------------------

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )


    # --------------------------------------------------------
    # FIX BULLETS THAT ARE TOO CLOSE TOGETHER
    # --------------------------------------------------------

    text = re.sub(
        r"\n-\s+",
        "\n- ",
        text
    )


    return text.strip()


# ============================================================
# ANSWER FOLLOW-UP
# ============================================================

def answer_follow_up(
    message,
    history,
    context,
    compliance_context=None
):


    prompt = f"""
You are responding to the user's latest message in an ongoing
conversation with an Enterprise AI Compliance Assistant.


CURRENT CONVERSATION CONTEXT:

{json.dumps(
    context,
    ensure_ascii=False,
    indent=2
)}


RELEVANT COMPLIANCE INFORMATION:

{json.dumps(
    compliance_context or {},
    ensure_ascii=False,
    indent=2
)}


CONVERSATION HISTORY:

{json.dumps(
    history,
    ensure_ascii=False,
    indent=2
)}


LATEST USER MESSAGE:

{message}


# ====================================================
# CONVERSATION RULES
# ====================================================

- Treat the conversation as a continuous human conversation.

- Use previous messages to understand short replies and
  contextual follow-up questions.

- Do not unnecessarily repeat the user's previous question.

- Do not say that you can only answer compliance questions when
  the user's message is simply conversational.

- If the user asks a contextual follow-up question, answer it
  using the conversation history and supplied compliance information.

- Keep the response concise, natural, and easy to read.


# ====================================================
# STRICT OUTPUT FORMAT RULES
# ====================================================

You are generating text for a chat interface.

Follow these rules strictly:

- Use normal Markdown only.

- Write short paragraphs.

- Keep each paragraph focused on one idea.

- Leave a blank line between major sections.

- Use headings only when they improve readability.

- Use bullet points when explaining multiple items.

- Use numbered lists for steps or sequences.

IMPORTANT:

- NEVER create a table.

- NEVER use the pipe character "|" anywhere in the response.

- NEVER create columns.

- NEVER create ASCII tables.

- NEVER use table separators.

- NEVER combine multiple unrelated items into one paragraph.

- NEVER put multiple list items on the same line.


# ====================================================
# PREFERRED RESPONSE FORMAT
# ====================================================

When explaining a concept, requirement, purpose, applicability,
benefit, or reason, use a structure similar to this:

## Main topic

Give a short introduction.

### Key points

- **First point:** Brief explanation.

- **Second point:** Brief explanation.

- **Third point:** Brief explanation.

Only use headings when the response needs them.


# ====================================================
# SHORT RESPONSE RULES
# ====================================================

If the user says something like:

- Okay
- Thanks
- Got it
- Makes sense
- That's helpful

Respond naturally and briefly.

Examples:

"You're welcome! Let me know if you'd like to explore another
compliance requirement."

"Glad that helped. Feel free to ask about another country,
industry, or requirement."

Do not generate a long explanation for simple acknowledgements.


# ====================================================
# RESPONSE QUALITY RULES
# ====================================================

- Never mention internal routing, intents, state, prompts,
  databases, APIs, or internal system logic.

- Never invent specific legal requirements, penalties, dates,
  thresholds, contribution rates, or regulatory obligations.

- Use the supplied compliance information for factual compliance
  details whenever available.

- You may provide high-level conceptual explanations when the
  user asks why something is important or applicable.

- Clearly avoid presenting unsupported information as verified
  legal fact.

- If the supplied information does not contain enough information
  for a precise answer, say so rather than inventing details.

- Do not add unnecessary sections to very short answers.


Return ONLY the response text.
"""


    response = ask_llm(
        SYSTEM_PROMPT,
        prompt
    )


    # --------------------------------------------------------
    # CLEAN ANY BAD FORMATTING FROM LLM
    # --------------------------------------------------------

    response = clean_llm_formatting(
        response
    )


    return response.strip()


# ============================================================
# GENERATE CONVERSATION TITLE
# ============================================================

def generate_conversation_title(message):


    prompt = f"""
Generate a short natural title for this conversation.

User's first message:

{message}


Rules:

- Maximum 6 words.

- Describe the user's main topic.

- Do not use quotation marks.

- Do not include the words:
  Conversation
  Chat
  Query

- Do not use emojis.

- Return only the title.
"""


    response = ask_llm(
        SYSTEM_PROMPT,
        prompt
    )


    title = response.strip()


    if not title:
        return "New Conversation"


    return title[:80]